# Objetivo específico 2 — Ingeniería de datos (ETL)

In [8]:
import pandas as pd

BASE_URL = (
    "https://raw.githubusercontent.com/"
    "adrianamarcelayavi-cmyk/"
    "inteligencia-negocios-series-temporales-supermercados/"
    "main/Objetivo_2_Diseno_ETL/datos"
)

def leer_csv_github(nombre):
    url = f"{BASE_URL}/{nombre}"
    return pd.read_csv(
        url,
        dtype=str,
        encoding="utf-8-sig"
    )

# Extracción automática de datos
df_original = leer_csv_github("DATOSHISTORICOSETL.csv")
df_catalogo = leer_csv_github("CATALOGOETL.csv")
df_sucursales = leer_csv_github("SUCURSALESETL.csv")

# Verificación
print("BASE CONSOLIDADA:", df_original.shape)
print("CATÁLOGO DE PRODUCTOS:", df_catalogo.shape)
print("SUCURSALES:", df_sucursales.shape)

print("\nCOLUMNAS DE CADA TABLA:")
print("Históricos:", df_original.columns.tolist())
print("Catálogo:", df_catalogo.columns.tolist())
print("Sucursales:", df_sucursales.columns.tolist())

BASE CONSOLIDADA: (1347, 8)
CATÁLOGO DE PRODUCTOS: (69, 4)
SUCURSALES: (7, 4)

COLUMNAS DE CADA TABLA:
Históricos: ['TIPO_REPORTE', 'FECHA', 'SUCURSAL', 'CANTIDAD', 'FECHA_VENCIMIENTO', 'PRODUCTO', 'CODIGO_BARRAS', 'CODIGO_PRODUCTO']
Catálogo: ['CODIGO_BARRAS', 'CODIGO_PRODUCTO', 'PRODUCTO', 'CATEGORIA_PRODUCTO']
Sucursales: ['SUCURSAL', 'DIRECCION', 'LATITUD', 'LONGITUD']

In [9]:
# ETL - TRANSFORMACIÓN DE DATOS
# PASO 2: Selección de columnas

columnas_principales = [
    "FECHA",
    "TIPO_REPORTE",
    "SUCURSAL",
    "CODIGO_BARRAS",
    "CODIGO_PRODUCTO",
    "PRODUCTO",
    "CANTIDAD",
    "FECHA_VENCIMIENTO"
]

# Trabajar con una copia de los datos originales
df = df_original[columnas_principales].copy()

# Verificar el resultado
print("DIMENSIONES DESPUÉS DE LA LIMPIEZA:", df.shape)

print("\nCOLUMNAS CONSERVADAS:")
print(df.columns.tolist())

display(df.head())

DIMENSIONES DESPUÉS DE LA LIMPIEZA: (1347, 8)

COLUMNAS CONSERVADAS:
['FECHA', 'TIPO_REPORTE', 'SUCURSAL', 'CODIGO_BARRAS', 'CODIGO_PRODUCTO', 'PRODUCTO', 'CANTIDAD', 'FECHA_VENCIMIENTO']

,FECHA,TIPO_REPORTE,SUCURSAL,CODIGO_BARRAS,CODIGO_PRODUCTO,PRODUCTO,CANTIDAD,FECHA_VENCIMIENTO
0,25/3/2026,PINCHADO,BLANCO GALINDO,BARRA_0002,32501,PRODUCTO_059,1,NaN
1,26/3/2026,PINCHADO,CIRCUNVALACIÓN,BARRA_0033,27818,PRODUCTO_386,1,NaN
2,26/3/2026,VENCIDO,CIRCUNVALACIÓN,BARRA_0053,28381,PRODUCTO_387,2,10/3/2026
3,27/3/2026,PINCHADO,CIRCUNVALACIÓN,BARRA_0014,10663,PRODUCTO_350,1,NaN
4,30/3/2026,VENCIDO,PRADO,BARRA_0060,32508,PRODUCTO_379,45,20/3/2026

TIPO DE DATOS

In [10]:
# ETL - TRANSFORMACIÓN DE DATOS
# PASO 3: Revisión de tipos de datos

print("INFORMACIÓN GENERAL DE LA BASE:")
df.info()

print("\nTIPOS DE DATOS POR COLUMNA:")
print(df.dtypes)

print("\nVALORES FALTANTES POR COLUMNA:")
print(df.isna().sum())

print("\nDIMENSIONES DE LA BASE:")
print(df.shape)

INFORMACIÓN GENERAL DE LA BASE:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1347 entries, 0 to 1346
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   FECHA              1347 non-null   object
 1   TIPO_REPORTE       1347 non-null   object
 2   SUCURSAL           1347 non-null   object
 3   CODIGO_BARRAS      1347 non-null   object
 4   CODIGO_PRODUCTO    1347 non-null   object
 5   PRODUCTO           1347 non-null   object
 6   CANTIDAD           1347 non-null   object
 7   FECHA_VENCIMIENTO  735 non-null    object
dtypes: object(8)
memory usage: 84.3+ KB

TIPOS DE DATOS POR COLUMNA:
FECHA                object
TIPO_REPORTE         object
SUCURSAL             object
CODIGO_BARRAS        object
CODIGO_PRODUCTO      object
PRODUCTO             object
CANTIDAD             object
FECHA_VENCIMIENTO    object
dtype: object

VALORES FALTANTES POR COLUMNA:
FECHA                  0
TIPO_REPORTE           0
SUCURSAL               0
CODIGO_BARRAS          0
CODIGO_PRODUCTO        0
PRODUCTO               0
CANTIDAD               0
FECHA_VENCIMIENTO    612
dtype: int64

DIMENSIONES DE LA BASE:
(1347, 8)

In [11]:
# ETL - TRANSFORMACIÓN DE DATOS
# PASO 4: Conversión de tipos de datos

# Fechas
for columna in ["FECHA", "FECHA_VENCIMIENTO"]:
    df[columna] = pd.to_datetime(
        df[columna],
        format="%d/%m/%Y",
        errors="coerce"
    )

# Variables categóricas
for columna in ["TIPO_REPORTE", "SUCURSAL"]:
    df[columna] = df[columna].astype("category")

# Identificadores
for columna in ["CODIGO_BARRAS", "CODIGO_PRODUCTO"]:
    df[columna] = df[columna].astype("string")

# Nombre completo del producto
df["PRODUCTO"] = df["PRODUCTO"].astype("string")

# Verificar conversiones
print("TIPOS DE DATOS:")
print(df.dtypes)

print("\nCATEGORÍAS DE TIPO_REPORTE:")
print(df["TIPO_REPORTE"].cat.categories.tolist())

print("\nCATEGORÍAS DE SUCURSAL:")
print(df["SUCURSAL"].cat.categories.tolist())

print("\nDIMENSIONES:")
print(df.shape)

TIPOS DE DATOS:
FECHA                datetime64[ns]
TIPO_REPORTE               category
SUCURSAL                   category
CODIGO_BARRAS        string[python]
CODIGO_PRODUCTO      string[python]
PRODUCTO             string[python]
CANTIDAD                     object
FECHA_VENCIMIENTO    datetime64[ns]
dtype: object

CATEGORÍAS DE TIPO_REPORTE:
['PINCHADO', 'PROXIMO', 'VENCIDO']

CATEGORÍAS DE SUCURSAL:
['BLANCO GALINDO', 'CIRCUNVALACIÓN', 'JUAN DE LA ROSA', 'PANAMERICANA', 'PRADO', 'SACABA', 'SOFFER']

DIMENSIONES:
(1347, 8)

In [12]:
# PASO 5: Validación de fechas y cantidades

print("VALORES FALTANTES:")
print(df.isna().sum())

print("\nFECHAS DE VENCIMIENTO FALTANTES POR REPORTE:")
print(
    df.groupby("TIPO_REPORTE", observed=True)
      ["FECHA_VENCIMIENTO"]
      .apply(lambda x: x.isna().sum())
)

print("\nCANTIDADES NULAS O NO POSITIVAS:")
print("Cantidades nulas:", df["CANTIDAD"].isna().sum())
# Convertir CANTIDAD a tipo numérico
df["CANTIDAD"] = pd.to_numeric(
    df["CANTIDAD"],
    errors="coerce"
)
print("Cantidades menores o iguales a cero:",
      (df["CANTIDAD"] <= 0).sum())

print("\nRANGO DE FECHAS DE REGISTRO:")
print("Fecha mínima:", df["FECHA"].min())
print("Fecha máxima:", df["FECHA"].max())

print("\nREGISTROS CONSERVADOS:", len(df))

VALORES FALTANTES:
FECHA                  0
TIPO_REPORTE           0
SUCURSAL               0
CODIGO_BARRAS          0
CODIGO_PRODUCTO        0
PRODUCTO               0
CANTIDAD               0
FECHA_VENCIMIENTO    612
dtype: int64

FECHAS DE VENCIMIENTO FALTANTES POR REPORTE:
TIPO_REPORTE
PINCHADO    612
PROXIMO       0
VENCIDO       0
Name: FECHA_VENCIMIENTO, dtype: int64

CANTIDADES NULAS O NO POSITIVAS:
Cantidades nulas: 0
Cantidades menores o iguales a cero: 0

RANGO DE FECHAS DE REGISTRO:
Fecha mínima: 2026-03-25 00:00:00
Fecha máxima: 2026-10-13 00:00:00

REGISTROS CONSERVADOS: 1347

REGISTROS DUPLICADOS

In [13]:
# PASO 6: Identificación de duplicados

# Detectar duplicados exactos
duplicados = df.duplicated(keep=False)

print("REGISTROS DUPLICADOS ADICIONALES:")
print(df.duplicated().sum())

print("\nFILAS INVOLUCRADAS EN DUPLICADOS:")
print(duplicados.sum())

# Mostrar los registros para revisión
if duplicados.any():
    display(df.loc[duplicados].sort_values(
        by=["FECHA", "SUCURSAL", "PRODUCTO"]
    ))
else:
    print("No se encontraron duplicados exactos.")

print("\nREGISTROS ACTUALES:", len(df))

REGISTROS DUPLICADOS ADICIONALES:
0

FILAS INVOLUCRADAS EN DUPLICADOS:
0
No se encontraron duplicados exactos.

REGISTROS ACTUALES: 1347

In [14]:
# PASO 7: Eliminación de duplicados exactos

# Guardar una copia antes de eliminar duplicados
df_antes_duplicados = df.copy()

# Cantidad inicial de registros
registros_antes = len(df)

# Eliminar duplicados exactos, conservando el primero
df = df.drop_duplicates(keep="first").reset_index(drop=True)

# Verificación
print("REGISTROS ANTES:", registros_antes)
print("DUPLICADOS ELIMINADOS:", registros_antes - len(df))
print("REGISTROS DESPUÉS:", len(df))
print("DUPLICADOS RESTANTES:", df.duplicated().sum())
print("DIMENSIONES FINALES:", df.shape)

REGISTROS ANTES: 1347
DUPLICADOS ELIMINADOS: 0
REGISTROS DESPUÉS: 1347
DUPLICADOS RESTANTES: 0
DIMENSIONES FINALES: (1347, 8)

VALORES NULOS

In [15]:
# PASO 8: Validación de valores nulos

print("VALORES NULOS POR COLUMNA:")
print(df.isna().sum())

print("\nPORCENTAJE DE VALORES NULOS:")
print((df.isna().mean() * 100).round(2))

print("\nFECHAS FALTANTES SEGÚN TIPO DE REPORTE:")
print(
    df.groupby("TIPO_REPORTE", observed=True)
      ["FECHA_VENCIMIENTO"]
      .apply(lambda x: x.isna().sum())
)

print("\nDIMENSIONES ACTUALES:")
print(df.shape)

VALORES NULOS POR COLUMNA:
FECHA                  0
TIPO_REPORTE           0
SUCURSAL               0
CODIGO_BARRAS          0
CODIGO_PRODUCTO        0
PRODUCTO               0
CANTIDAD               0
FECHA_VENCIMIENTO    612
dtype: int64

PORCENTAJE DE VALORES NULOS:
FECHA                 0.00
TIPO_REPORTE          0.00
SUCURSAL              0.00
CODIGO_BARRAS         0.00
CODIGO_PRODUCTO       0.00
PRODUCTO              0.00
CANTIDAD              0.00
FECHA_VENCIMIENTO    45.43
dtype: float64

FECHAS FALTANTES SEGÚN TIPO DE REPORTE:
TIPO_REPORTE
PINCHADO    612
PROXIMO       0
VENCIDO       0
Name: FECHA_VENCIMIENTO, dtype: int64

DIMENSIONES ACTUALES:
(1347, 8)

ESTANDARIZACIÓN DE TEXTOS

In [16]:
# PASO 9: Limpieza y estandarización de textos

columnas_texto = [
    "TIPO_REPORTE",
    "SUCURSAL",
    "PRODUCTO"
]

# Conservar los valores anteriores para comparar
textos_antes = df[columnas_texto].copy()

# Convertir temporalmente a texto y normalizar
for columna in columnas_texto:
    df[columna] = (
        df[columna]
        .astype("string")
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
        .str.upper()
    )

# Restaurar tipo categórico donde corresponde
df["TIPO_REPORTE"] = df["TIPO_REPORTE"].astype("category")
df["SUCURSAL"] = df["SUCURSAL"].astype("category")

# Contar valores modificados por columna
print("VALORES MODIFICADOS:")
for columna in columnas_texto:
    cambios = (
        textos_antes[columna].astype("string")
        != df[columna].astype("string")
    ).fillna(False).sum()

    print(f"{columna}: {cambios}")

print("\nTIPOS DE REPORTE:")
print(df["TIPO_REPORTE"].cat.categories.tolist())

print("\nSUCURSALES:")
print(df["SUCURSAL"].cat.categories.tolist())

print("\nDIMENSIONES:")
print(df.shape)

VALORES MODIFICADOS:
TIPO_REPORTE: 0
SUCURSAL: 0
PRODUCTO: 0

TIPOS DE REPORTE:
['PINCHADO', 'PROXIMO', 'VENCIDO']

SUCURSALES:
['BLANCO GALINDO', 'CIRCUNVALACIÓN', 'JUAN DE LA ROSA', 'PANAMERICANA', 'PRADO', 'SACABA', 'SOFFER']

DIMENSIONES:
(1347, 8)

ESTANDARIZAR MEDIANTE CATÁLOGO MAESTRO

In [17]:
# PASO 10: Resolver claves duplicadas del catálogo maestro
maestro_limpio = df_catalogo.copy()
claves = ["CODIGO_BARRAS", "CODIGO_PRODUCTO"]
for columna in claves:
    maestro_limpio[columna] = maestro_limpio[columna].astype("string").str.strip()

# Identificar diferencias de denominación para la misma combinación de códigos.
conflictos = maestro_limpio[maestro_limpio.duplicated(subset=claves, keep=False)]
print("FILAS CON CLAVES REPETIDAS EN EL CATÁLOGO:", len(conflictos))
if not conflictos.empty:
    print("ATENCIÓN: se conservará la primera aparición de cada clave. "
          "Revisa que sea la denominación autorizada antes de utilizar la base.")
# La clave debe ser única para la validación many_to_one posterior.
maestro_limpio = maestro_limpio.drop_duplicates(subset=claves, keep="first").copy()
print("REGISTROS DEL CATÁLOGO:", len(maestro_limpio))
print("PARES DUPLICADOS RESTANTES:", maestro_limpio.duplicated(subset=claves).sum())

FILAS CON CLAVES REPETIDAS EN EL CATÁLOGO: 2
ATENCIÓN: se conservará la primera aparición de cada clave. Revisa que sea la denominación autorizada antes de utilizar la base.
REGISTROS DEL CATÁLOGO: 68
PARES DUPLICADOS RESTANTES: 0

COINCIDENCIA DE PARES DE CÓDIGOS

In [18]:
# PASO 11: Validación con el catálogo limpio

claves = ["CODIGO_BARRAS", "CODIGO_PRODUCTO"]

# Crear copias para la comparación
base_validacion = df.copy()
catalogo_validacion = maestro_limpio.copy()

# Uniformar los códigos como texto
for columna in claves:
    base_validacion[columna] = (
        base_validacion[columna].astype("string").str.strip()
    )
    catalogo_validacion[columna] = (
        catalogo_validacion[columna].astype("string").str.strip()
    )

# Comparar ambos códigos
validacion_productos = base_validacion.merge(
    catalogo_validacion[claves + ["PRODUCTO"]].rename(
        columns={"PRODUCTO": "PRODUCTO_MAESTRO"}
    ),
    on=claves,
    how="left",
    validate="many_to_one",
    indicator=True
)

# Mostrar resultados
print("REGISTROS ORIGINALES:", len(df))
print("REGISTROS DESPUÉS DE LA COMPARACIÓN:",
      len(validacion_productos))

print("\nRESULTADO DE LA VALIDACIÓN:")
print(validacion_productos["_merge"].value_counts())

print("\nREGISTROS SIN CORRESPONDENCIA:")
print((validacion_productos["_merge"] == "left_only").sum())

print("\nDIMENSIONES:")
print(validacion_productos.shape)

REGISTROS ORIGINALES: 1347
REGISTROS DESPUÉS DE LA COMPARACIÓN: 1347

RESULTADO DE LA VALIDACIÓN:
_merge
both          1345
left_only        2
right_only       0
Name: count, dtype: int64

REGISTROS SIN CORRESPONDENCIA:
2

DIMENSIONES:
(1347, 10)

REVISIÓN DE REGISTROS SIN COINCIDENCIA

In [19]:
# PASO 12: Revisar registros sin correspondencia

sin_correspondencia = validacion_productos[
    validacion_productos["_merge"] == "left_only"
].copy()

print("REGISTROS SIN CORRESPONDENCIA:")
print(len(sin_correspondencia))

display(
    sin_correspondencia[
        [
            "FECHA",
            "SUCURSAL",
            "CODIGO_BARRAS",
            "CODIGO_PRODUCTO",
            "PRODUCTO",
            "PRODUCTO_MAESTRO"
        ]
    ]
)

print("\nCONTROL DE REGISTROS:")
print("Base original importada:", len(df_original))
print("Base transformada:", len(df))
print("Diferencia:", len(df_original) - len(df))

REGISTROS SIN CORRESPONDENCIA:
2

,FECHA,SUCURSAL,CODIGO_BARRAS,CODIGO_PRODUCTO,PRODUCTO,PRODUCTO_MAESTRO
156,2026-04-20,PRADO,BARRA_0028,550185,PRODUCTO_039,NaN
166,2026-04-21,CIRCUNVALACIÓN,BARRA_0028,550185,PRODUCTO_039,NaN

CONTROL DE REGISTROS:
Base original importada: 1347
Base transformada: 1347
Diferencia: 0

In [20]:
# PASO 13: Exclusión de productos eventuales

# Conservar por separado los registros excluidos
df_eventuales = validacion_productos[
    validacion_productos["_merge"] == "left_only"
].copy()

# Conservar los registros validados con el catálogo
df_validado = validacion_productos[
    validacion_productos["_merge"] == "both"
].copy()

# Eliminar únicamente la columna auxiliar de validación
df_validado = df_validado.drop(columns=["_merge"])

# Verificar resultados
print("REGISTROS ANTES:", len(validacion_productos))
print("PRODUCTOS EVENTUALES EXCLUIDOS:", len(df_eventuales))
print("REGISTROS CONSERVADOS:", len(df_validado))

print("\nCONTROL DE CONSERVACIÓN:")
print(len(df_eventuales) + len(df_validado))

display(
    df_eventuales[
        ["CODIGO_BARRAS", "CODIGO_PRODUCTO", "PRODUCTO"]
    ].drop_duplicates()
)

REGISTROS ANTES: 1347
PRODUCTOS EVENTUALES EXCLUIDOS: 2
REGISTROS CONSERVADOS: 1345

CONTROL DE CONSERVACIÓN:
1347

    CODIGO_BARRAS CODIGO_PRODUCTO      PRODUCTO
156    BARRA_0028          550185  PRODUCTO_039

ESTANDARIZACIÓN DE NOMBRES

In [21]:
# ETL - TRANSFORMACIÓN DE DATOS
# PASO 14: Estandarización de nombres de productos

# Crear una copia de los registros validados
df_limpio = df_validado.copy()

# Conservar el nombre registrado originalmente
df_limpio["PRODUCTO_ORIGINAL"] = df_limpio["PRODUCTO"].copy()

# Asignar el nombre del catálogo maestro
df_limpio["PRODUCTO"] = (
    df_limpio["PRODUCTO_MAESTRO"]
    .astype("string")
    .str.strip()
    .str.upper()
)

# Eliminar la columna auxiliar
df_limpio = df_limpio.drop(columns=["PRODUCTO_MAESTRO"])

# Verificar resultados
print("REGISTROS CONSERVADOS:", len(df_limpio))

print("\nPRODUCTOS SIN NOMBRE:")
print(df_limpio["PRODUCTO"].isna().sum())

print("\nNOMBRES DISTINTOS ESTANDARIZADOS:")
print(df_limpio["PRODUCTO"].nunique())

print("\nCOMPARACIÓN DE NOMBRES:")
display(
    df_limpio[
        ["CODIGO_BARRAS",
         "CODIGO_PRODUCTO",
         "PRODUCTO_ORIGINAL",
         "PRODUCTO"]
    ].head(15)
)

REGISTROS CONSERVADOS: 1345

PRODUCTOS SIN NOMBRE:
0

NOMBRES DISTINTOS ESTANDARIZADOS:
57

COMPARACIÓN DE NOMBRES:

   CODIGO_BARRAS CODIGO_PRODUCTO PRODUCTO_ORIGINAL      PRODUCTO
0     BARRA_0002           32501      PRODUCTO_059  PRODUCTO_059
1     BARRA_0033           27818      PRODUCTO_386  PRODUCTO_386
2     BARRA_0053           28381      PRODUCTO_387  PRODUCTO_387
3     BARRA_0014           10663      PRODUCTO_350  PRODUCTO_350
4     BARRA_0060           32508      PRODUCTO_379  PRODUCTO_379
5     BARRA_0039           28338      PRODUCTO_102  PRODUCTO_102
6     BARRA_0040           28337      PRODUCTO_363  PRODUCTO_363
7     BARRA_0035           27413      PRODUCTO_341  PRODUCTO_341
8     BARRA_0066           30920      PRODUCTO_317  PRODUCTO_317
9     BARRA_0040           28337      PRODUCTO_363  PRODUCTO_363
10    BARRA_0043           29600      PRODUCTO_381  PRODUCTO_381
11    BARRA_0067           31418      PRODUCTO_355  PRODUCTO_355
12    BARRA_0043           29600      PRODUCTO_381  PRODUCTO_381
13    BARRA_0042           30377      PRODUCTO_382  PRODUCTO_382
14    BARRA_0017           27819      PRODUCTO_295  PRODUCTO_295

In [22]:
# PASO 15: Verificación de QUILMES y QUILLMES

# Buscar ambas variantes en la base estandarizada
revision_quilmes = df_limpio[
    df_limpio["PRODUCTO"].str.contains(
        r"QUILMES|QUILLMES",
        case=False,
        na=False
    )
]

print("NOMBRES EN LA BASE ESTANDARIZADA:")
print(revision_quilmes["PRODUCTO"].value_counts())

print("\nREGISTROS CON QUILLMES (DOBLE L):")
errores = df_limpio[
    df_limpio["PRODUCTO"].str.contains(
        "QUILLMES", case=False, na=False
    )
]
print(len(errores))

print("\nCÓDIGOS Y NOMBRES IDENTIFICADOS:")
display(
    revision_quilmes[
        ["CODIGO_BARRAS", "CODIGO_PRODUCTO", "PRODUCTO"]
    ].drop_duplicates()
)

NOMBRES EN LA BASE ESTANDARIZADA:
Series([], Name: count, dtype: Int64)

REGISTROS CON QUILLMES (DOBLE L):
0

CÓDIGOS Y NOMBRES IDENTIFICADOS:

Empty DataFrame
Columns: [CODIGO_BARRAS, CODIGO_PRODUCTO, PRODUCTO]
Index: []

ESTANDARIZACIÓN DE SUCURSALES

In [23]:
# PASO 16: Verificación de sucursales

print("COLUMNAS DEL CATÁLOGO DE SUCURSALES:")
print(df_sucursales.columns.tolist())

print("\nCATÁLOGO DE SUCURSALES:")
display(df_sucursales)

print("\nSUCURSALES EN LA BASE TRANSFORMADA:")
print(df_limpio["SUCURSAL"].value_counts())

print("\nCANTIDAD DE SUCURSALES DISTINTAS:")
print(df_limpio["SUCURSAL"].nunique())

COLUMNAS DEL CATÁLOGO DE SUCURSALES:
['SUCURSAL', 'DIRECCION', 'LATITUD', 'LONGITUD']

CATÁLOGO DE SUCURSALES:

,SUCURSAL,DIRECCION,LATITUD,LONGITUD
0,SACABA,"Av. Eliodoro Villazón, Sacaba, Cochabamba",-17.39,-66.1
1,CIRCUNVALACIÓN,"Av. Circunvalación, Cochabamba",-17.3697,-66.1554
2,JUAN DE LA ROSA,"Av. Juan de la Rosa, Cochabamba",-17.3776,-66.1668
3,BLANCO GALINDO,"Av. Blanco Galindo, Cochabamba",-17.394,-66.1824
4,PANAMERICANA,"Av. Panamericana, Cochabamba",-17.4145,-66.1557
5,SOFFER,"Av. Oquendo, Cochabamba",-17.3847,-66.1508
6,PRADO,"Av. José Ballivián, Cochabamba",-17.3844,-66.1591

SUCURSALES EN LA BASE TRANSFORMADA:
SUCURSAL
BLANCO GALINDO     289
PRADO              240
SACABA             216
CIRCUNVALACIÓN     210
PANAMERICANA       138
SOFFER             134
JUAN DE LA ROSA    118
Name: count, dtype: int64

CANTIDAD DE SUCURSALES DISTINTAS:
7

In [24]:
# PASO 17: Validación de sucursales

# Obtener nombres del catálogo
sucursales_maestras = set(
    df_sucursales["SUCURSAL"]
    .astype("string")
    .str.strip()
    .str.upper()
)

# Obtener nombres de la base transformada
sucursales_base = set(
    df_limpio["SUCURSAL"]
    .astype("string")
    .str.strip()
    .str.upper()
)

# Identificar sucursales sin correspondencia
sin_correspondencia = (
    sucursales_base - sucursales_maestras
)

print("SUCURSALES EN EL CATÁLOGO:",
      len(sucursales_maestras))

print("SUCURSALES EN LA BASE:",
      len(sucursales_base))

print("SUCURSALES SIN CORRESPONDENCIA:",
      len(sin_correspondencia))

print("\nDETALLE:")
print(sorted(sin_correspondencia))

print("\nREGISTROS CONSERVADOS:",
      len(df_limpio))

SUCURSALES EN EL CATÁLOGO: 7
SUCURSALES EN LA BASE: 7
SUCURSALES SIN CORRESPONDENCIA: 0

DETALLE:
[]

REGISTROS CONSERVADOS: 1345

VALIDACIÓN DE COHERENCIA DE FECHAS

In [25]:
# PASO 18: Validación de coherencia de fechas

# Crear copia para revisión
revision_fechas = df_limpio.copy()

# Identificar inconsistencias
vencidos_incorrectos = (
    (revision_fechas["TIPO_REPORTE"] == "VENCIDO") &
    (
        revision_fechas["FECHA_VENCIMIENTO"].isna() |
        (revision_fechas["FECHA_VENCIMIENTO"] >
         revision_fechas["FECHA"])
    )
)

proximos_incorrectos = (
    (revision_fechas["TIPO_REPORTE"] == "PROXIMO") &
    (
        revision_fechas["FECHA_VENCIMIENTO"].isna() |
        (revision_fechas["FECHA_VENCIMIENTO"] <=
         revision_fechas["FECHA"])
    )
)

# Unir las inconsistencias identificadas
inconsistencias = revision_fechas[
    vencidos_incorrectos | proximos_incorrectos
]

print("VENCIDOS CON FECHAS INCONSISTENTES:",
      vencidos_incorrectos.sum())

print("PRÓXIMOS CON FECHAS INCONSISTENTES:",
      proximos_incorrectos.sum())

print("TOTAL DE REGISTROS A REVISAR:",
      len(inconsistencias))

display(
    inconsistencias[
        ["FECHA", "TIPO_REPORTE", "SUCURSAL",
         "PRODUCTO", "FECHA_VENCIMIENTO"]
    ].head(20)
)

VENCIDOS CON FECHAS INCONSISTENTES: 11
PRÓXIMOS CON FECHAS INCONSISTENTES: 2
TOTAL DE REGISTROS A REVISAR: 13

          FECHA TIPO_REPORTE        SUCURSAL      PRODUCTO FECHA_VENCIMIENTO
56   2026-04-09      VENCIDO          SACABA  PRODUCTO_363        2026-09-20
68   2026-04-13      VENCIDO           PRADO  PRODUCTO_350        2026-04-18
70   2026-04-13      VENCIDO           PRADO  PRODUCTO_363        2026-04-14
112  2026-04-14      VENCIDO  BLANCO GALINDO  PRODUCTO_102        2026-06-04
163  2026-04-20      VENCIDO           PRADO  PRODUCTO_341        2026-04-21
194  2026-04-21      VENCIDO  CIRCUNVALACIÓN  PRODUCTO_304        2026-04-23
274  2026-05-11      VENCIDO  BLANCO GALINDO  PRODUCTO_371        2026-08-16
335  2026-06-01      VENCIDO    PANAMERICANA  PRODUCTO_059        2026-06-07
373  2026-06-16      VENCIDO          SACABA  PRODUCTO_355        2026-06-19
417  2026-07-08      VENCIDO          SOFFER  PRODUCTO_392        2026-07-09
431  2026-07-26      PROXIMO          SACABA  PRODUCTO_378        2003-03-20
1127 2026-09-23      PROXIMO          SACABA  PRODUCTO_363        2026-09-05
1269 2026-10-06      VENCIDO          SOFFER  PRODUCTO_298        2026-10-08

In [26]:
# PASO 19: Clasificación de inconsistencias de fechas

import numpy as np

# Copia para revisión
df_revision = df_limpio.copy()

# Identificar inconsistencias
condiciones = [
    (df_revision["TIPO_REPORTE"] == "VENCIDO") &
    (df_revision["FECHA_VENCIMIENTO"] > df_revision["FECHA"]),

    (df_revision["TIPO_REPORTE"] == "PROXIMO") &
    (df_revision["FECHA_VENCIMIENTO"] <= df_revision["FECHA"])
]

descripciones = [
    "VENCIDO CON FECHA FUTURA",
    "PROXIMO CON FECHA VENCIDA"
]

# Agregar estado de validación
df_revision["ESTADO_FECHA"] = np.select(
    condiciones,
    descripciones,
    default="CORRECTO SEGUN REGLA"
)

print("RESUMEN DE VALIDACIÓN:")
print(df_revision["ESTADO_FECHA"].value_counts())

print("\nREGISTROS PARA REVISIÓN:")
display(
    df_revision[
        df_revision["ESTADO_FECHA"] != "CORRECTO SEGUN REGLA"
    ][
        ["FECHA", "TIPO_REPORTE", "SUCURSAL",
         "PRODUCTO", "FECHA_VENCIMIENTO",
         "ESTADO_FECHA"]
    ]
)

RESUMEN DE VALIDACIÓN:
ESTADO_FECHA
CORRECTO SEGUN REGLA         1332
VENCIDO CON FECHA FUTURA       11
PROXIMO CON FECHA VENCIDA       2
Name: count, dtype: int64

REGISTROS PARA REVISIÓN:

,FECHA,TIPO_REPORTE,SUCURSAL,PRODUCTO,FECHA_VENCIMIENTO,ESTADO_FECHA
56,2026-04-09,VENCIDO,SACABA,PRODUCTO_363,2026-09-20,VENCIDO CON FECHA FUTURA
68,2026-04-13,VENCIDO,PRADO,PRODUCTO_350,2026-04-18,VENCIDO CON FECHA FUTURA
70,2026-04-13,VENCIDO,PRADO,PRODUCTO_363,2026-04-14,VENCIDO CON FECHA FUTURA
112,2026-04-14,VENCIDO,BLANCO GALINDO,PRODUCTO_102,2026-06-04,VENCIDO CON FECHA FUTURA
163,2026-04-20,VENCIDO,PRADO,PRODUCTO_341,2026-04-21,VENCIDO CON FECHA FUTURA
194,2026-04-21,VENCIDO,CIRCUNVALACIÓN,PRODUCTO_304,2026-04-23,VENCIDO CON FECHA FUTURA
274,2026-05-11,VENCIDO,BLANCO GALINDO,PRODUCTO_371,2026-08-16,VENCIDO CON FECHA FUTURA
335,2026-06-01,VENCIDO,PANAMERICANA,PRODUCTO_059,2026-06-07,VENCIDO CON FECHA FUTURA
373,2026-06-16,VENCIDO,SACABA,PRODUCTO_355,2026-06-19,VENCIDO CON FECHA FUTURA
417,2026-07-08,VENCIDO,SOFFER,PRODUCTO_392,2026-07-09,VENCIDO CON FECHA FUTURA
431,2026-07-26,PROXIMO,SACABA,PRODUCTO_378,2003-03-20,PROXIMO CON FECHA VENCIDA
1127,2026-09-23,PROXIMO,SACABA,PRODUCTO_363,2026-09-05,PROXIMO CON FECHA VENCIDA
1269,2026-10-06,VENCIDO,SOFFER,PRODUCTO_298,2026-10-08,VENCIDO CON FECHA FUTURA

In [27]:
# PASO 20: Separación de registros inconsistentes

# Registros que cumplen las reglas
df_correctos = df_revision[
    df_revision["ESTADO_FECHA"] == "CORRECTO SEGUN REGLA"
].copy()

# Registros que requieren corrección
df_por_corregir = df_revision[
    df_revision["ESTADO_FECHA"] != "CORRECTO SEGUN REGLA"
].copy()

# Verificación
print("REGISTROS CORRECTOS:", len(df_correctos))
print("REGISTROS POR CORREGIR:", len(df_por_corregir))

print("TOTAL CONTROLADO:",
      len(df_correctos) + len(df_por_corregir))

display(
    df_por_corregir[
        ["FECHA", "TIPO_REPORTE", "SUCURSAL",
         "PRODUCTO", "FECHA_VENCIMIENTO",
         "ESTADO_FECHA"]
    ]
)

REGISTROS CORRECTOS: 1332
REGISTROS POR CORREGIR: 13
TOTAL CONTROLADO: 1345

,FECHA,TIPO_REPORTE,SUCURSAL,PRODUCTO,FECHA_VENCIMIENTO,ESTADO_FECHA
56,2026-04-09,VENCIDO,SACABA,PRODUCTO_363,2026-09-20,VENCIDO CON FECHA FUTURA
68,2026-04-13,VENCIDO,PRADO,PRODUCTO_350,2026-04-18,VENCIDO CON FECHA FUTURA
70,2026-04-13,VENCIDO,PRADO,PRODUCTO_363,2026-04-14,VENCIDO CON FECHA FUTURA
112,2026-04-14,VENCIDO,BLANCO GALINDO,PRODUCTO_102,2026-06-04,VENCIDO CON FECHA FUTURA
163,2026-04-20,VENCIDO,PRADO,PRODUCTO_341,2026-04-21,VENCIDO CON FECHA FUTURA
194,2026-04-21,VENCIDO,CIRCUNVALACIÓN,PRODUCTO_304,2026-04-23,VENCIDO CON FECHA FUTURA
274,2026-05-11,VENCIDO,BLANCO GALINDO,PRODUCTO_371,2026-08-16,VENCIDO CON FECHA FUTURA
335,2026-06-01,VENCIDO,PANAMERICANA,PRODUCTO_059,2026-06-07,VENCIDO CON FECHA FUTURA
373,2026-06-16,VENCIDO,SACABA,PRODUCTO_355,2026-06-19,VENCIDO CON FECHA FUTURA
417,2026-07-08,VENCIDO,SOFFER,PRODUCTO_392,2026-07-09,VENCIDO CON FECHA FUTURA
431,2026-07-26,PROXIMO,SACABA,PRODUCTO_378,2003-03-20,PROXIMO CON FECHA VENCIDA
1127,2026-09-23,PROXIMO,SACABA,PRODUCTO_363,2026-09-05,PROXIMO CON FECHA VENCIDA
1269,2026-10-06,VENCIDO,SOFFER,PRODUCTO_298,2026-10-08,VENCIDO CON FECHA FUTURA

In [28]:
# PASO 21: Preparar tabla de correcciones

columnas_revision = [
    "FECHA",
    "TIPO_REPORTE",
    "SUCURSAL",
    "CODIGO_BARRAS",
    "CODIGO_PRODUCTO",
    "PRODUCTO",
    "FECHA_VENCIMIENTO",
    "ESTADO_FECHA"
]

tabla_correcciones = df_por_corregir[
    columnas_revision
].copy()

# Conservar el índice para identificar cada registro
tabla_correcciones.insert(
    0, "ID_REGISTRO", tabla_correcciones.index
)

# Campos para documentar las correcciones
tabla_correcciones["CAMPO_A_CORREGIR"] = ""
tabla_correcciones["VALOR_CORRECTO"] = ""
tabla_correcciones["OBSERVACION"] = ""

print("REGISTROS PARA REVISIÓN:", len(tabla_correcciones))

display(tabla_correcciones)

REGISTROS PARA REVISIÓN: 13

,ID_REGISTRO,FECHA,TIPO_REPORTE,SUCURSAL,CODIGO_BARRAS,CODIGO_PRODUCTO,PRODUCTO,FECHA_VENCIMIENTO,ESTADO_FECHA,CAMPO_A_CORREGIR,VALOR_CORRECTO,OBSERVACION
56,56,2026-04-09,VENCIDO,SACABA,BARRA_0040,28337,PRODUCTO_363,2026-09-20,VENCIDO CON FECHA FUTURA,,,
68,68,2026-04-13,VENCIDO,PRADO,BARRA_0014,10663,PRODUCTO_350,2026-04-18,VENCIDO CON FECHA FUTURA,,,
70,70,2026-04-13,VENCIDO,PRADO,BARRA_0040,28337,PRODUCTO_363,2026-04-14,VENCIDO CON FECHA FUTURA,,,
112,112,2026-04-14,VENCIDO,BLANCO GALINDO,BARRA_0039,28338,PRODUCTO_102,2026-06-04,VENCIDO CON FECHA FUTURA,,,
163,163,2026-04-20,VENCIDO,PRADO,BARRA_0035,27413,PRODUCTO_341,2026-04-21,VENCIDO CON FECHA FUTURA,,,
194,194,2026-04-21,VENCIDO,CIRCUNVALACIÓN,BARRA_0007,20004,PRODUCTO_304,2026-04-23,VENCIDO CON FECHA FUTURA,,,
274,274,2026-05-11,VENCIDO,BLANCO GALINDO,BARRA_0050,30664,PRODUCTO_371,2026-08-16,VENCIDO CON FECHA FUTURA,,,
335,335,2026-06-01,VENCIDO,PANAMERICANA,BARRA_0002,32501,PRODUCTO_059,2026-06-07,VENCIDO CON FECHA FUTURA,,,
373,373,2026-06-16,VENCIDO,SACABA,BARRA_0067,31418,PRODUCTO_355,2026-06-19,VENCIDO CON FECHA FUTURA,,,
417,417,2026-07-08,VENCIDO,SOFFER,BARRA_0034,31644,PRODUCTO_392,2026-07-09,VENCIDO CON FECHA FUTURA,,,
431,431,2026-07-26,PROXIMO,SACABA,BARRA_0018,26437,PRODUCTO_378,2003-03-20,PROXIMO CON FECHA VENCIDA,,,
1127,1127,2026-09-23,PROXIMO,SACABA,BARRA_0040,28337,PRODUCTO_363,2026-09-05,PROXIMO CON FECHA VENCIDA,,,
1269,1269,2026-10-06,VENCIDO,SOFFER,BARRA_0057,32485,PRODUCTO_298,2026-10-08,VENCIDO CON FECHA FUTURA,,,

In [29]:
# PASO 22: Propuesta de reclasificación lógica

# Trabajar sobre una copia
df_propuesta = df_limpio.copy()

# Conservar la clasificación original
df_propuesta["TIPO_REPORTE_ORIGINAL"] = (
    df_propuesta["TIPO_REPORTE"].astype("string")
)

# Crear clasificación propuesta
df_propuesta["TIPO_REPORTE_PROPUESTO"] = (
    df_propuesta["TIPO_REPORTE"].astype("string")
)

# Solo revisar VENCIDO y PROXIMO
revisables = df_propuesta["TIPO_REPORTE"].isin(
    ["VENCIDO", "PROXIMO"]
)

fecha_valida = df_propuesta["FECHA_VENCIMIENTO"].notna()

# Reclasificar según la relación entre fechas
vencidos = (
    revisables & fecha_valida &
    (df_propuesta["FECHA_VENCIMIENTO"] <= df_propuesta["FECHA"])
)

proximos = (
    revisables & fecha_valida &
    (df_propuesta["FECHA_VENCIMIENTO"] > df_propuesta["FECHA"])
)

df_propuesta.loc[
    vencidos, "TIPO_REPORTE_PROPUESTO"
] = "VENCIDO"

df_propuesta.loc[
    proximos, "TIPO_REPORTE_PROPUESTO"
] = "PROXIMO"

# Marcar fecha antigua sospechosa
df_propuesta["REVISAR_FECHA"] = (
    df_propuesta["FECHA_VENCIMIENTO"].dt.year.lt(2020)
    .fillna(False)
)

# Mostrar solamente cambios propuestos
cambios = df_propuesta[
    df_propuesta["TIPO_REPORTE_ORIGINAL"] !=
    df_propuesta["TIPO_REPORTE_PROPUESTO"]
]

print("CAMBIOS DE CLASIFICACIÓN PROPUESTOS:", len(cambios))
print("FECHAS ANTIGUAS PARA REVISIÓN:",
      df_propuesta["REVISAR_FECHA"].sum())

display(cambios[[
    "FECHA", "PRODUCTO", "TIPO_REPORTE_ORIGINAL",
    "TIPO_REPORTE_PROPUESTO", "FECHA_VENCIMIENTO",
    "REVISAR_FECHA"
]])

CAMBIOS DE CLASIFICACIÓN PROPUESTOS: 13
FECHAS ANTIGUAS PARA REVISIÓN: 1

,FECHA,PRODUCTO,TIPO_REPORTE_ORIGINAL,TIPO_REPORTE_PROPUESTO,FECHA_VENCIMIENTO,REVISAR_FECHA
56,2026-04-09,PRODUCTO_363,VENCIDO,PROXIMO,2026-09-20,False
68,2026-04-13,PRODUCTO_350,VENCIDO,PROXIMO,2026-04-18,False
70,2026-04-13,PRODUCTO_363,VENCIDO,PROXIMO,2026-04-14,False
112,2026-04-14,PRODUCTO_102,VENCIDO,PROXIMO,2026-06-04,False
163,2026-04-20,PRODUCTO_341,VENCIDO,PROXIMO,2026-04-21,False
194,2026-04-21,PRODUCTO_304,VENCIDO,PROXIMO,2026-04-23,False
274,2026-05-11,PRODUCTO_371,VENCIDO,PROXIMO,2026-08-16,False
335,2026-06-01,PRODUCTO_059,VENCIDO,PROXIMO,2026-06-07,False
373,2026-06-16,PRODUCTO_355,VENCIDO,PROXIMO,2026-06-19,False
417,2026-07-08,PRODUCTO_392,VENCIDO,PROXIMO,2026-07-09,False
431,2026-07-26,PRODUCTO_378,PROXIMO,VENCIDO,2003-03-20,True
1127,2026-09-23,PRODUCTO_363,PROXIMO,VENCIDO,2026-09-05,False
1269,2026-10-06,PRODUCTO_298,VENCIDO,PROXIMO,2026-10-08,False

In [30]:
# PASO 23: Aplicar reclasificación lógica

# Crear copia de trabajo
df_corregido = df_propuesta.copy()

# Identificar cambios que no tienen fecha sospechosa
cambios_aplicables = (
    (
        df_corregido["TIPO_REPORTE_ORIGINAL"] !=
        df_corregido["TIPO_REPORTE_PROPUESTO"]
    )
    & (~df_corregido["REVISAR_FECHA"])
)

# Aplicar cambios de clasificación
df_corregido["TIPO_REPORTE"] = (
    df_corregido["TIPO_REPORTE"].astype("string")
)

df_corregido.loc[
    cambios_aplicables, "TIPO_REPORTE"
] = df_corregido.loc[
    cambios_aplicables, "TIPO_REPORTE_PROPUESTO"
]

# Restaurar tipo categórico
df_corregido["TIPO_REPORTE"] = (
    df_corregido["TIPO_REPORTE"].astype("category")
)

print("RECLASIFICACIONES APLICADAS:",
      cambios_aplicables.sum())

print("REGISTROS PENDIENTES POR FECHA SOSPECHOSA:",
      df_corregido["REVISAR_FECHA"].sum())

print("REGISTROS CONSERVADOS:", len(df_corregido))

RECLASIFICACIONES APLICADAS: 12
REGISTROS PENDIENTES POR FECHA SOSPECHOSA: 1
REGISTROS CONSERVADOS: 1345

In [31]:
# PASO 24: Verificación de las reclasificaciones

# VENCIDO: vencimiento anterior o igual al reporte
error_vencido = (
    (df_corregido["TIPO_REPORTE"] == "VENCIDO") &
    (
        df_corregido["FECHA_VENCIMIENTO"].isna() |
        (df_corregido["FECHA_VENCIMIENTO"] > df_corregido["FECHA"])
    )
)

# PROXIMO: vencimiento posterior al reporte
error_proximo = (
    (df_corregido["TIPO_REPORTE"] == "PROXIMO") &
    (
        df_corregido["FECHA_VENCIMIENTO"].isna() |
        (df_corregido["FECHA_VENCIMIENTO"] <= df_corregido["FECHA"])
    )
)

print("INCONSISTENCIAS TEMPORALES RESTANTES:",
      (error_vencido | error_proximo).sum())

print("FECHAS SOSPECHOSAS PENDIENTES:",
      df_corregido["REVISAR_FECHA"].sum())

print("REGISTROS CONSERVADOS:", len(df_corregido))

print("\nREGISTRO PENDIENTE:")
display(
    df_corregido.loc[
        df_corregido["REVISAR_FECHA"],
        ["FECHA", "TIPO_REPORTE", "SUCURSAL",
         "PRODUCTO", "FECHA_VENCIMIENTO"]
    ]
)

INCONSISTENCIAS TEMPORALES RESTANTES: 1
FECHAS SOSPECHOSAS PENDIENTES: 1
REGISTROS CONSERVADOS: 1345

REGISTRO PENDIENTE:

         FECHA TIPO_REPORTE SUCURSAL      PRODUCTO FECHA_VENCIMIENTO
431 2026-07-26      PROXIMO   SACABA  PRODUCTO_378        2003-03-20

In [32]:
# PASO 25: Eliminación del registro incorrecto

# Conservar copia para trazabilidad
df_registro_eliminado = df_corregido[
    df_corregido["REVISAR_FECHA"]
].copy()

# Eliminar de la base de análisis
df_final = df_corregido[
    ~df_corregido["REVISAR_FECHA"]
].copy()

# Reiniciar índices
df_final = df_final.reset_index(drop=True)

# Verificar resultados
print("REGISTROS ANTES:", len(df_corregido))
print("REGISTROS ELIMINADOS:", len(df_registro_eliminado))
print("REGISTROS FINALES:", len(df_final))

print("\nFECHAS SOSPECHOSAS RESTANTES:")
print(df_final["REVISAR_FECHA"].sum())

REGISTROS ANTES: 1345
REGISTROS ELIMINADOS: 1
REGISTROS FINALES: 1344

FECHAS SOSPECHOSAS RESTANTES:
0

In [33]:
# ETL - TRANSFORMACIÓN DE DATOS
# PASO 26: Control final de calidad

print("DIMENSIONES DE LA BASE:")
print(df_final.shape)

print("\nVALORES NULOS:")
print(df_final.isna().sum())

print("\nDUPLICADOS EXACTOS:")
print(df_final.duplicated(
    subset=[
        "FECHA", "TIPO_REPORTE", "SUCURSAL",
        "CODIGO_BARRAS", "CODIGO_PRODUCTO",
        "PRODUCTO", "CANTIDAD", "FECHA_VENCIMIENTO"
    ]
).sum())

print("\nCANTIDADES NO POSITIVAS:")
print((df_final["CANTIDAD"] <= 0).sum())

print("\nREGISTROS POR TIPO DE REPORTE:")
print(df_final["TIPO_REPORTE"].value_counts())

# Verificar coherencia temporal
error_vencido = (
    (df_final["TIPO_REPORTE"] == "VENCIDO") &
    (df_final["FECHA_VENCIMIENTO"] > df_final["FECHA"])
)

error_proximo = (
    (df_final["TIPO_REPORTE"] == "PROXIMO") &
    (df_final["FECHA_VENCIMIENTO"] <= df_final["FECHA"])
)

print("\nINCONSISTENCIAS DE FECHAS:")
print((error_vencido | error_proximo).sum())

print("\nPRODUCTOS DISTINTOS:")
print(df_final["PRODUCTO"].nunique())

print("\nSUCURSALES DISTINTAS:")
print(df_final["SUCURSAL"].nunique())

DIMENSIONES DE LA BASE:
(1344, 12)

VALORES NULOS:
FECHA                       0
TIPO_REPORTE                0
SUCURSAL                    0
CODIGO_BARRAS               0
CODIGO_PRODUCTO             0
PRODUCTO                    0
CANTIDAD                    0
FECHA_VENCIMIENTO         610
PRODUCTO_ORIGINAL           0
TIPO_REPORTE_ORIGINAL       0
TIPO_REPORTE_PROPUESTO      0
REVISAR_FECHA               0
dtype: int64

DUPLICADOS EXACTOS:
0

CANTIDADES NO POSITIVAS:
0

REGISTROS POR TIPO DE REPORTE:
TIPO_REPORTE
PINCHADO    610
VENCIDO     496
PROXIMO     238
Name: count, dtype: int64

INCONSISTENCIAS DE FECHAS:
0

PRODUCTOS DISTINTOS:
57

SUCURSALES DISTINTAS:
7

In [34]:
# PASO 27: Preparar la base analítica

columnas_finales = [
    "FECHA",
    "TIPO_REPORTE",
    "SUCURSAL",
    "CODIGO_BARRAS",
    "CODIGO_PRODUCTO",
    "PRODUCTO",
    "CANTIDAD",
    "FECHA_VENCIMIENTO"
]

# Conservar una copia con las columnas auxiliares
df_trazabilidad = df_final.copy()

# Crear la base destinada al análisis
df_analitico = df_final[columnas_finales].copy()

print("BASE ANALÍTICA:", df_analitico.shape)
print("BASE DE TRAZABILIDAD:", df_trazabilidad.shape)

print("\nCOLUMNAS DE LA BASE ANALÍTICA:")
print(df_analitico.columns.tolist())

display(df_analitico.head())

BASE ANALÍTICA: (1344, 8)
BASE DE TRAZABILIDAD: (1344, 12)

COLUMNAS DE LA BASE ANALÍTICA:
['FECHA', 'TIPO_REPORTE', 'SUCURSAL', 'CODIGO_BARRAS', 'CODIGO_PRODUCTO', 'PRODUCTO', 'CANTIDAD', 'FECHA_VENCIMIENTO']

,FECHA,TIPO_REPORTE,SUCURSAL,CODIGO_BARRAS,CODIGO_PRODUCTO,PRODUCTO,CANTIDAD,FECHA_VENCIMIENTO
0,2026-03-25,PINCHADO,BLANCO GALINDO,BARRA_0002,32501,PRODUCTO_059,1,NaT
1,2026-03-26,PINCHADO,CIRCUNVALACIÓN,BARRA_0033,27818,PRODUCTO_386,1,NaT
2,2026-03-26,VENCIDO,CIRCUNVALACIÓN,BARRA_0053,28381,PRODUCTO_387,2,2026-03-10
3,2026-03-27,PINCHADO,CIRCUNVALACIÓN,BARRA_0014,10663,PRODUCTO_350,1,NaT
4,2026-03-30,VENCIDO,PRADO,BARRA_0060,32508,PRODUCTO_379,45,2026-03-20

In [35]:
# PASO 28: Control de procedencia de la base

print("REGISTROS DE LA FUENTE ACTUAL:")
print(len(df_original))

print("\nREGISTROS DESPUÉS DE LA TRANSFORMACIÓN:")
print(len(df_analitico))

print("\nREGISTROS EXCLUIDOS POR PRODUCTOS EVENTUALES:")
print(len(df_eventuales))

print("\nREGISTROS EXCLUIDOS POR FECHA INCORRECTA:")
print(len(df_registro_eliminado))

print("\nCONTROL:")
print(
    "Total contabilizado:",
    len(df_analitico)
    + len(df_eventuales)
    + len(df_registro_eliminado)
)

REGISTROS DE LA FUENTE ACTUAL:
1347

REGISTROS DESPUÉS DE LA TRANSFORMACIÓN:
1344

REGISTROS EXCLUIDOS POR PRODUCTOS EVENTUALES:
2

REGISTROS EXCLUIDOS POR FECHA INCORRECTA:
1

CONTROL:
Total contabilizado: 1347

In [36]:
# PASO 29: Exportación de datos transformados

# Guardar base analítica
df_analitico.to_csv(
    "datos_transformados.csv",
    index=False,
    encoding="utf-8-sig"
)

# Guardar trazabilidad de las transformaciones
df_trazabilidad.to_csv(
    "trazabilidad_transformaciones.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Archivos generados correctamente.")
print("Registros analíticos:", len(df_analitico))
print("Registros de trazabilidad:", len(df_trazabilidad))

Archivos generados correctamente.
Registros analíticos: 1344
Registros de trazabilidad: 1344

In [37]:
# PASO 30: Verificación de los archivos transformados

import pandas as pd

# Leer el archivo generado por el ETL
df_verificacion = pd.read_csv(
    "datos_transformados.csv",
    dtype={
        "CODIGO_BARRAS": "string",
        "CODIGO_PRODUCTO": "string"
    }
)

print("DIMENSIONES:", df_verificacion.shape)

print("\nCOLUMNAS:")
print(df_verificacion.columns.tolist())

print("\nREGISTROS POR TIPO:")
print(df_verificacion["TIPO_REPORTE"].value_counts())

print("\nDUPLICADOS EXACTOS:")
print(df_verificacion.duplicated().sum())

DIMENSIONES: (1344, 8)

COLUMNAS:
['FECHA', 'TIPO_REPORTE', 'SUCURSAL', 'CODIGO_BARRAS', 'CODIGO_PRODUCTO', 'PRODUCTO', 'CANTIDAD', 'FECHA_VENCIMIENTO']

REGISTROS POR TIPO:
TIPO_REPORTE
PINCHADO    610
VENCIDO     496
PROXIMO     238
Name: count, dtype: int64

DUPLICADOS EXACTOS:
0

In [38]:
# PASO 31: Comprobación final del ETL

print("BASE ORIGINAL:", df_original.shape)
print("BASE TRANSFORMADA:", df_analitico.shape)

print("\nREGISTROS POR TIPO:")
print(df_analitico["TIPO_REPORTE"].value_counts())

print("\nDUPLICADOS RESTANTES:")
print(df_analitico.duplicated().sum())

BASE ORIGINAL: (1347, 8)
BASE TRANSFORMADA: (1344, 8)

REGISTROS POR TIPO:
TIPO_REPORTE
PINCHADO    610
VENCIDO     496
PROXIMO     238
Name: count, dtype: int64

DUPLICADOS RESTANTES:
0

In [39]:
# PASO 32: Verificación final de tipos de datos

print("TIPOS DE DATOS DE LA BASE ANALÍTICA:")
print(df_analitico.dtypes)

print("\nVALORES NULOS POR COLUMNA:")
print(df_analitico.isna().sum())

print("\nRESUMEN FINAL:")
df_analitico.info()

TIPOS DE DATOS DE LA BASE ANALÍTICA:
FECHA                datetime64[ns]
TIPO_REPORTE               category
SUCURSAL                   category
CODIGO_BARRAS        string[python]
CODIGO_PRODUCTO      string[python]
PRODUCTO             string[python]
CANTIDAD                      int64
FECHA_VENCIMIENTO    datetime64[ns]
dtype: object

VALORES NULOS POR COLUMNA:
FECHA                  0
TIPO_REPORTE           0
SUCURSAL               0
CODIGO_BARRAS          0
CODIGO_PRODUCTO        0
PRODUCTO               0
CANTIDAD               0
FECHA_VENCIMIENTO    610
dtype: int64

RESUMEN FINAL:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1344 entries, 0 to 1343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   FECHA              1344 non-null   datetime64[ns]
 1   TIPO_REPORTE       1344 non-null   category
 2   SUCURSAL           1344 non-null   category
 3   CODIGO_BARRAS      1344 non-null   string
 4   CODIGO_PRODUCTO    1344 non-null   string
 5   PRODUCTO           1344 non-null   string
 6   CANTIDAD           1344 non-null   int64
 7   FECHA_VENCIMIENTO  734 non-null    datetime64[ns]
dtypes: category(2), datetime64[ns](2), int64(1), string(3)
memory usage: 66.2 KB

In [40]:
# PASO 33: Exportación complementaria para análisis exploratorio
df_analitico.to_csv(
    "datos_limpios_EDA.csv", index=False, encoding="utf-8-sig"
)
print("Archivo datos_limpios_EDA.csv generado en el entorno de Colab.")
# Descarga opcional: desde el panel Archivos de Google Colab.

Archivo datos_limpios_EDA.csv generado en el entorno de Colab.